# use new or old data_preprocessing
NEW_DATA: True

# use data_preprocessing augmentation
DATA_AUGMENTATION: False

# label format: 'one-per-item' (19-dimensional), 'three-per-item' (55-dimensiona), or 'one' (only complete score)
LABEL_FORMAT: one

# show debug prints
DEBUG: True

# redo loading and preprocessing of labels from disk
REDO_PREPROCESSING_LABELS: False

# redo loading and preprocessing of images from disk
REDO_PREPROCESSING_IMAGES: False

# True for Regressor, False for Classifier
REGRESSOR_MODE: True

# load only a few images for preprocessing, faster to test
LOAD_ONLY_FEW: False

# use binning: 'none' to use original scores, 'discrete' to use fixed integer binning, 'continuous' for continuous binning
BINNING: 'none'

# validate on binning, even if binning wasn't used for training
VAL_BINNING: False

# specify number of convolutional layers [2..4]
CONV_LAYERS: 4

# dropout
DROPOUT: 0.8

# define how many images you want to use, provide 0 if all
CONVERGENCE: 0

# model to be restored
MODEL_PATH: '../summaries/model_fold0.ckpt'

# test can be False (normal cross-val on train/val) or True (train on all training data_preprocessing, test on test data_preprocessing)
TEST: False

# classification encoding: 'one-hot' (0,0,1,0,0), 'weighted' (0.05,0.1,0.7,0.1,0.05), 'ordinal' (1, 1, 1, 0, 0)
CLASSIFICATION_ENCODER: 'one-hot'

# compute intermediate features (currently only works if no preprocessing must be done)
INTERMEDIATES: False

# Directory which should be watched for new created images
DIRECTORY_TO_WATCH: '/Users/stephan/Desktop/images'

# Directory to write demo output images to (must end on /!)
DEST_PATH: '/Users/stephan/Desktop/results/'

# define fold you want to skip (if run failed before)
SKIP_FOLDS:
 - 0
 - 1